services:
  postgres:
    container_name: ParkingSlots.DB
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: parking-slot
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data 
  api:
    container_name: ParkingSlots.API
    build: 
      context: .
      args:
        - DATABASE_HOST=postgres
        - DATABASE_PORT=5432
        - DATABASE_NAME=parking-slot
        - DATABASE_USER=root
        - DATABASE_PASSWORD=root
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_NAME: parking-slot
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
    command: ["sh", "-c", "npm run migration:run:final && node dist/main"]